### ISSUE TITLE
where is jshint-emacs-path?

### ISSUE THREAD

**Issue by rwillmer** [daleharvey/jshint-mode#1]
<code>
git clone git://github.com/daleharvey/jshint-mode.gitj
cd jshint-mode
jshint-emacs-path >> ~/.emacs
-bash: jshint-emacs-path: command not found
<code>

what/where is it?

**Comment by daleharvey** [comment]
jshint-emacs-path is only installed when npm is used to install, it just spits out the config filled in

(add-to-list 'load-path "~/path/to/jshint-mode")
(require 'flymake-jshint)
(add-hook 'javascript-mode-hook
     (lambda () (flymake-mode t)))

**Comment by rwillmer** [comment]
I'm going to hazard a guess that there's some dependency on npm/nodejs for this to work. Would be useful to have this documented before you start installing.

(Looks very useful, btw!)

**Comment by daleharvey** [comment]
ah yeh it needs node.js installed to work, I should document that a bit better, sorry about that
